### ISSUE TITLE
Mirror does not respond to commands on second iPhone connect.

### ISSUE THREAD

**Issue by blaaat** [Lange90/Mirror#1]
The Mirror only responds to `0xE0, 0x40` or `0xE0, 0x23` commands on the first connect to the iPhone. 

After the first connect; the iPhone shows the "Pair" alert and Mirror is stuck in "App paused" screen, even though app sends above commands. 

When we go to iPhone Bluetooth settings, and forget the connected Mirror. It works once on re-connect.

**Comment by Lange90** [comment]
https://www.youtube.com/watch?v=xp6k44dVCGM

`0xE0, 0x23` is being sent each 2-3 seconds.

**Comment by echowell-byron** [comment]
ANS: Current version during our staff test , can not re-produce this issue. 
     and the BBB test version APP ,have limit date , we can not used from today ! please release new version of test APP !

**Comment by echowell-byron** [comment]
please confirm your question is , if APP already stay on Start menu mode , then power on the Computer , 
but the computer do not display "Start" menu just display "APP pause" ,  please check when APP already stay on Start menu mode will contiunue send 0X0E 0X23 command to computer or not ?
