### ISSUE TITLE
Lap data is displaying Total time/distance from 0xFF lap number

### ISSUE THREAD

**Issue by blaaat** [Lange90/Mirror#11]
The mirror displays the total time/distance sent with 0xD2 0xFF command for Lap; 
should use data sent in 0xD2 0xLAPNUMBER command. 

Last lap = Display data from LAP: (current LAPNUMBER - 1)

**Comment by Lange90** [comment]
![img_20170213_120408](https://cloud.githubusercontent.com/assets/25738998/22881400/8f247070-f1e6-11e6-8881-ec8f17198526.jpg)

Lap data out of sync

**Comment by echowell-byron** [comment]
ANS : if need to do this change , just only display computer received Lap data update value form APP , will cause a couple of seconds delay,
