### ISSUE TITLE
Unable to dismiss ANCS pair

### ISSUE THREAD

**Issue by blaaat** [Lange90/Mirror#13]
User is not able to dismiss "Pair" with ios bluetooth.

**Comment by Lange90** [comment]
https://www.youtube.com/watch?v=rGmYGHaUWBo

**Comment by echowell-byron** [comment]
ANS: Current version during our staff test , can not re-produce this issue. 
     and the BBB test version APP ,have limit date , we can not used from today ! please release new version of test APP !

**Comment by echowell-byron** [comment]
ANS: it is control by iOS system not by our computer !
