### ISSUE TITLE
iOS shows "Pair" / ANCS confirm box on each reconnect.

### ISSUE THREAD

**Issue by blaaat** [Lange90/Mirror#3]
Usually devices Pair once; and don't show the 'Pair' box on a reconnect. 
Please fix Pair message on each reconnect.

**Comment by Lange90** [comment]
https://www.youtube.com/watch?v=FBbAbiOnI_Y

**Comment by echowell-byron** [comment]
ANS:  IOS show"pair "box on each re-connect => it is control by iOS system not by our computer !  how we can fix it ?
