### ISSUE TITLE
Heading value does not update

### ISSUE THREAD

**Issue by blaaat** [Lange90/Mirror#4]
When focussed on the 'heading' value. The value does only change when pressing the button. 
See video.

**Comment by Lange90** [comment]
Example video:
https://youtu.be/2moQ-hkobUc

**Comment by echowell-byron** [comment]
ANS:  Current version do not definition "heading value " show update or alert should be "display it on different screen "
      if need to do this change , need to definition which screen should always update heading ? or it show alert same as incoming call/message at any screen ? 
      please confirm your definition ! ?
