### ISSUE TITLE
When in riding mode, we cannot go back to 'Start workout' screen

### ISSUE THREAD

**Issue by blaaat** [Lange90/Mirror#5]
After sending 

`0xE0, 0x23` 

We cannot go back to workout screen by sending

`0xE0, 0x40`

**Comment by echowell-byron** [comment]
ANS: Current version only definition "Start" menu at power on screen , not at riding mode.
if need to do this change , need to add definition "Start" at riding mode.
Please confirm your want change the definition ! ?
