### ISSUE TITLE
Sensor state in 0xC0 should be leading

### ISSUE THREAD

**Issue by blaaat** [Lange90/Mirror#7]
We sent the sensor state in each 0xC0 update. This sensor state should be leading. 

**We don't want to use the 0xD4 command, we don't want to overwrite mirror ANT+ Settings**

So in 0xC0, byte 14, the bluetooth sensor status is sent to the mirror: 

**Sensor bit = 1 (speed or cadence, or HR)** 

- Display the data sent with 0xC0 command
- Ignore all ANT+ sensors
- Do not search for ANT+ sensors

**Sensor bit = 0 (speed or cadence, or HR)** 

- display GPS speed; sent with 0xC0 command. 
- Try to connect to ANT+ sensor for 60 seconds
- If ANT+ sensor connected, display ANT+ speed/cadence/HR
- If no ANT+ sensor connected; keep using GPS speed.

**Comment by echowell-byron** [comment]
•	ANS : this change is the definition change, as above change , is talking about bit 4 Heading available ( GPS) =1 ?  or 0 ? 
we need you definition more detail of how to process it  if bit 4 Heading available ( GPS) =1  how to process ? and bit 4 Heading available ( GPS) = 0  how to process ? 
and just process once when 0xC0, byte 14, the bluetooth sensor status is change ?
